import { CATEGORY_PLEDGES } from "./pledges"

export const CATEGORIES = [
  { id: "future", title: "미래도시", subtitle: "개발이익은 시민에게, 미래산업은 남양주에", icon: "Building2", count: 20, progress: 45, color: "bg-blue-500", topPledges: ["남양주형 개발이익 환수 및 공공재투자 추진", "환수된 개발이익 GTX 및 생활SOC 재투자", "왕숙 첨단 클러스터 조성"] },
  { id: "economy", title: "경제·민생·일자리", subtitle: "풍요롭고 활기찬 자족도시 남양주", icon: "TrendingUp", count: 47, progress: 60, color: "bg-green-500", topPledges: ["남양주 시민은행 설립 추진", "저신용자·소상공인·금융취약계층 대상 초저금리 소액대출 지원", "소상공인 카드수수료 지원"] },
  { id: "transport", title: "교통", subtitle: "사통팔달 어디로든 통하는 교통허브", icon: "TrainFront", count: 22, progress: 30, color: "bg-indigo-500", topPledges: ["GTX-B/D/E/F 조기 추진 및 광역철도망 연계", "9호선·8호선·6호선 연장 및 3호선 덕소 연결 추진", "수석대교 6차선 직결 추진"] },
  { id: "living", title: "도시·주거", subtitle: "쾌적하고 살기 좋은 명품 주거환경", icon: "Home", count: 21, progress: 55, color: "bg-orange-500", topPledges: ["시립 공동주택 관리공단 설립 추진", "통합관리시스템 구축을 통한 반값 관리비 실현", "소규모 공동주택 관리 사각지대 해소"] },
  { id: "admin", title: "자치·행정", subtitle: "시민이 주인이 되는 참여행정 실현", icon: "Users", count: 28, progress: 80, color: "bg-teal-500", topPledges: ["전시민투표제 기반 ‘남양주 쓸모앱’ 도입", "권역별·현안별 타운홀미팅, 시민해커톤 운영 등 숙의민주주의 확대", "주민참여예산 대폭 확대"] },
  { id: "welfare", title: "복지·돌봄·장애인·노인", subtitle: "사각지대 없는 따뜻한 맞춤형 복지", icon: "HeartHandshake", count: 83, progress: 40, color: "bg-rose-500", topPledges: ["경기도립의료원 남양주병원 조기 착공 및 완공 추진", "상급종합병원급 협력체계 구축 및 대학병원 유치 추진", "남양주 SOS 돌봄119 운영"] },
  { id: "youth", title: "아동·여성·청년", subtitle: "아이 키우기 좋고 청년이 꿈꾸는 도시", icon: "Baby", count: 25, progress: 65, color: "bg-pink-500", topPledges: ["여성센터 건립 추진", "디지털 성범죄·스토킹 통합대응체계 구축 및 강화", "역세권 청년주거 공급 확대"] },
  { id: "culture", title: "문화·예술·관광", subtitle: "일상이 예술이 되는 문화관광 으뜸도시", icon: "Palette", count: 41, progress: 50, color: "bg-purple-500", topPledges: ["1,000석 이상 대형 문화예술회관(아트센터) 조성", "‘조선로열 이음(IEUM)’ 역사문화벨트 조성", "광릉·사릉·홍유릉 역사탐방 루트 구축"] },
  { id: "education", title: "교육", subtitle: "배움의 즐거움이 가득한 미래교육도시", icon: "GraduationCap", count: 25, progress: 70, color: "bg-yellow-500", topPledges: ["권역별 시민캠퍼스 및 시민대학 운영", "남양주 독립 교육지원청 추진", "화도권 고등학교 신설 및 과밀학급 정상화"] },
  { id: "environment", title: "환경·기후·에너지", subtitle: "자연과 사람이 공존하는 친환경 생태도시", icon: "Leaf", count: 16, progress: 85, color: "bg-emerald-500", topPledges: ["시민참여형 햇빛발전 및 햇빛연금 확대", "공공 RE100 기반 에너지 자립도시 추진", "‘남양주형 그린페이’ 등 에너지 마일리지 도입"] },
]

export const REGIONS = [
  { id: "gap", name: "갑구", areas: ["화도읍", "호평동", "수동면", "평내동", "갑구공통"] },
  { id: "eul", name: "을구", areas: ["진접읍", "오남읍", "별내동", "별내면", "을구공통"] },
  { id: "byeong", name: "병구", areas: ["와부읍", "진건읍", "다산1동", "다산2동", "퇴계원읍", "금곡동", "조안면", "양정동", "병구공통"] },
]

export const POLICY_STATUSES = [
  { id: "예산확보", label: "예산확보", color: "warning" },
  { id: "추진중", label: "추진중", color: "default" },
  { id: "완료", label: "완료", color: "success" },
]

const REAL_PLEDGES = [
  { title: "GTX-B 마석역세권 랜드마크 추진", region: "화도읍", cat: "transport", department: "미래교통과" },
  { title: "화도IC 직결 광역버스 노선 신설 추진", region: "화도읍", cat: "transport", department: "대중교통과" },
  { title: "인문계 고등학교 신설 추진", region: "화도읍", cat: "education", department: "미래교육과" },
  { title: "원도심 생태친수공간 조성 추진", region: "화도읍", cat: "environment", department: "환경정책과" },
  { title: "화도 제2체육문화센터 건립 추진", region: "화도읍", cat: "culture", department: "체육지원과" },
  { title: "동부경찰서 화도읍 유치 추진", region: "화도읍", cat: "admin", department: "시민안전과" },
  { title: "하천(구운천, 월문천, 궁촌천, 도심천, 덕소천) 생태친수공간(공원) 조성 추진", region: "화도읍", cat: "environment", department: "생태하천과" },
  { title: "삼패 공원-팔당 구간 공원 조성 추진", region: "화도읍", cat: "environment", department: "공원조성과" },
  { title: "도곡리 고려대ㆍ연세대 농장 부지 공공 개방 협의 추진", region: "화도읍", cat: "culture", department: "공원조성과" },
  { title: "유휴지(철도부지 등) 소공원 조성", region: "화도읍", cat: "environment", department: "공원조성과" },
  { title: "동양하루살이 방제", region: "화도읍", cat: "environment", department: "보건정책과" },
  { title: "마석LIG아파트 안전한 통학로 확보 추진(대형화물 주차장조성 후 대형화물차 통행으로 안전통학 위협)", region: "화도읍", cat: "transport", department: "도로건설과" },

  { title: "평내호평역 환승센터 및 출입구 신설(3번출구) 추진", region: "호평동", cat: "transport", department: "미래교통과" },
  { title: "호만천 미디어아트 활용 빛축제 개최 추진", region: "호평동", cat: "culture", department: "문화예술과" },
  { title: "천마산 일대 둘레길 추진(호평-화도-오남)", region: "호평동", cat: "environment", department: "공원조성과" },
  { title: "지하철 9호선 평내호평 연장·분선 추진", region: "호평동", cat: "transport", department: "미래교통과" },

  { title: "난개발 방지 지구단위계획 수립 추진", region: "수동면", cat: "living", department: "도시정책과" },
  { title: "수동천(구운천) 생태길, 안전한 보행도로 조성", region: "수동면", cat: "environment", department: "생태하천과" },
  { title: "구운천 둔치공원 등 조성", region: "수동면", cat: "environment", department: "생태하천과" },
  { title: "자전거길 한강 연결(가평군-대성리 구간 협력)", region: "수동면", cat: "environment", department: "도로건설과" },
  { title: "몽골문화촌 활성화 및 체험형 관광지 조성 추진", region: "수동면", cat: "culture", department: "문화예술과" },
  { title: "축령산, 물맑음수목원, 몽골문화촌 입장료 페이백(지역 상권 유입으로 연계 방안 마련 필요)", region: "수동면", cat: "economy", department: "소상공인과" },
  { title: "제2순환고속도로 신호·요금체계 개선 추진", region: "수동면", cat: "transport", department: "도로건설과" },
  { title: "내부정체 심각, 버스 증차", region: "수동면", cat: "transport", department: "대중교통과" },
  { title: "공영주차장 확대", region: "수동면", cat: "transport", department: "주차관리과" },
  { title: "뉴턴 구간 확대", region: "수동면", cat: "transport", department: "대중교통과" },
  { title: "불법 펜션(농촌 생활형 숙박) 단속", region: "수동면", cat: "living", department: "도시정책과" },
  { title: "상하수도 설치 확대", region: "수동면", cat: "living", department: "상하수도관리센터" },
  { title: "경기동북부형 에버랜드 수동 추진", region: "수동면", cat: "culture", department: "문화관광과" },
  { title: "신한성 골프장 수익 수동 재투자(100억 확인)", region: "수동면", cat: "economy", department: "기획예산과" },

  { title: "경기도립병원 예타 면제 및 조기 착공 추진", region: "평내동", cat: "welfare", department: "보건정책과" },
  { title: "평내 제4지구 개발 조속 추진", region: "평내동", cat: "living", department: "도시정책과" },
  { title: "궁집 관광특화거리·지역상권 활성화 추진", region: "평내동", cat: "culture", department: "소상공인과" },
  { title: "백봉산 등산로 정비 추진", region: "평내동", cat: "environment", department: "공원조성과" },

  { title: "경춘선 셔틀 상시 운행", region: "갑구공통", cat: "transport", department: "대중교통과" },
  { title: "경춘선, 수인분당선 직결 추진", region: "갑구공통", cat: "transport", department: "미래교통과" },

  { title: "4호선, 9호선 환승역 풍양역(가칭) 설치 조속 추진", region: "진접읍", cat: "transport", department: "미래교통과" },
  { title: "9호선 기본계획에 따른 개통을 위한 조기착공 추진", region: "진접읍", cat: "transport", department: "미래교통과" },
  { title: "군부대 이전 부지 체육·문화 복합공간으로 활용 추진", region: "진접읍", cat: "culture", department: "체육지원과" },
  { title: "장현 전통시장 현대화 및 상권 활성화 추진", region: "진접읍", cat: "economy", department: "소상공인과" },
  { title: "왕숙천 상류 하천 및 주변 환경정비사업 추진", region: "진접읍", cat: "environment", department: "생태하천과" },
  { title: "진접역 역세권 활성화(대학 캠퍼스타운, 문화복합단지)", region: "진접읍", cat: "living", department: "도시계획과" },
  { title: "왕숙1지구내 대형 아트홀 건립 추진", region: "진접읍", cat: "culture", department: "문화예술과" },
  { title: "금곡교차로 개선 조속 추진", region: "진접읍", cat: "transport", department: "도로건설과" },
  { title: "시도5호선(중말~철마교차로) 도로 확장 조기 완공 추진", region: "진접읍", cat: "transport", department: "도로건설과" },
  { title: "천겸산 전망대 및 케이블카, 종합문화예술관 설치 추진", region: "진접읍", cat: "culture", department: "문화관광과" },
  { title: "장현공원 농구장 이용 전환 (카약체험장 등) 추진", region: "진접읍", cat: "culture", department: "공원관리과" },
  { title: "광릉내 854 정비부대 철수 후 자연생태공원 조성 추진", region: "진접읍", cat: "environment", department: "공원조성과" },
  { title: "국지도 98호선 접지지역 복합아웃렛 유치 추진", region: "진접읍", cat: "economy", department: "미래성장과" },
  { title: "반려동물 테마파크 유치 추진", region: "진접읍", cat: "culture", department: "농축산지원과" },
  { title: "경기신용보증기금, 남양주세무서, 창업지원센터 등 유치 추진", region: "진접읍", cat: "economy", department: "기업지원과" },
  { title: "도심형종합터미널 조성 추진", region: "진접읍", cat: "transport", department: "대중교통과" },
  { title: "진접읍 행사 인프라 구축(주택용지 활용)", region: "진접읍", cat: "culture", department: "문화예술과" },

  { title: "오남천~오남호수공원 수변힐링벨트 조성 추진", region: "오남읍", cat: "environment", department: "생태하천과" },
  { title: "오남사거리 입체교차로 조기 완공 추진", region: "오남읍", cat: "transport", department: "도로환경과" },
  { title: "오남~별내·진접 연결 광역버스 확대 추진", region: "오남읍", cat: "transport", department: "대중교통과" },
  { title: "지방도383호선(진건~오남) 개설사업 조기 추진", region: "오남읍", cat: "transport", department: "도로건설과" },
  { title: "오남호수공원 무대 환경개선", region: "오남읍", cat: "culture", department: "공원관리과" },

  { title: "8호선 별내역~별내별가람역 연결 및 중앙역 신설 추진", region: "별내동", cat: "transport", department: "미래교통과" },
  { title: "별내 광역환승센터 및 주차타워 건립 추진", region: "별내동", cat: "transport", department: "미래교통과" },
  { title: "경춘선 ITX 청춘열차 별내역 정차 추진", region: "별내동", cat: "transport", department: "대중교통과" },
  { title: "출근시간 버스 증차 및 배차시간 단축 추진", region: "별내동", cat: "transport", department: "대중교통과" },
  { title: "용암천 정비 및 카페거리 활성화 추진", region: "별내동", cat: "economy", department: "소상공인과" },
  { title: "지역 내 군 유휴지 활용 주민 이용시설 추진(문화시설 등)", region: "별내동", cat: "living", department: "도시정책과" },
  { title: "4호선(진접선) 배차 간격 조정", region: "별내동", cat: "transport", department: "대중교통과" },
  { title: "상업(2,7)부지 개발 추진", region: "별내동", cat: "living", department: "도시활성화과" },
  { title: "차고지 문제 해결", region: "별내동", cat: "transport", department: "대중교통과" },
  { title: "소각장 및 별내에너지 이익공유(클린넷 유지 보수 등)", region: "별내동", cat: "environment", department: "자원순환과" },
  { title: "물류창고 일부공간 주민이용 활용", region: "별내동", cat: "living", department: "주민복지과" },
  { title: "별내별가람역 4번출구 버스정거장 확대로 보행환경 악화", region: "별내동", cat: "transport", department: "미래교통과" },

  { title: "8호선 별내역~별내별가람역~청학역(신설)~의정부 연장추진", region: "별내면", cat: "transport", department: "미래교통과" },
  { title: "별내면~별내동 간 용암천 정비 및 자전거도로 개설", region: "별내면", cat: "environment", department: "생태하천과" },
  { title: "606 수송부대 이전 전면 백지화", region: "별내면", cat: "living", department: "도시정책과" },
  { title: "별내면~별내동 용암천 정비사업 및 자전거도로(산책로) 신설 조속 추진", region: "별내면", cat: "environment", department: "생태하천과" },
  { title: "별내 내부 교통만 개선으로 이동편의 증진", region: "별내면", cat: "transport", department: "대중교통과" },
  { title: "불암산역 방면 버스 증차 추진", region: "별내면", cat: "transport", department: "대중교통과" },
  { title: "별내면사무소 앞 도로 개선 조기 추진", region: "별내면", cat: "transport", department: "도로건설과" },
  { title: "별내면 송산로 373번지 9-14 농수산물 창고 비산먼지 피해", region: "별내면", cat: "environment", department: "환경정책과" },

  { title: "진접~오남 둘레길 조성 추진", region: "을구공통", cat: "environment", department: "공원조성과" },
  { title: "KBS 역사 박물관 유치 추진", region: "을구공통", cat: "culture", department: "문화예술과" },
  { title: "진접~벌안산 터널건설", region: "을구공통", cat: "transport", department: "도로건설과" },
  { title: "주거지 주변 창고, 공장 이전", region: "을구공통", cat: "living", department: "도시계획과" },
  { title: "북부복합문화 공연장 유치", region: "을구공통", cat: "culture", department: "문화예술과" },
  { title: "진접역, 오남역 버스 배차 및 환승체계 개선", region: "을구공통", cat: "transport", department: "대중교통과" },
  { title: "오남역, 진접 연평4거리 주변 용도 변경 추진", region: "을구공통", cat: "living", department: "도시개발과" },
  { title: "남양주(진접, 평내호평, 덕소)~하남 민자고속도로 건설 추진", region: "을구공통", cat: "transport", department: "도로건설과" },
  { title: "전기선 지중화(오남읍, 양지리, 장현리, 부평리 등)", region: "을구공통", cat: "living", department: "도시정비과" },

  { title: "국지도 86호선 확장 및 보행로 신설 추진", region: "와부읍", cat: "transport", department: "도로건설과" },
  { title: "덕소역 출입구 추가 신설 추진", region: "와부읍", cat: "transport", department: "미래교통과" },
  { title: "덕소~하남 간 셔틀버스 운행 추진", region: "와부읍", cat: "transport", department: "대중교통과" },
  { title: "경의중앙선 증차 및 팔당역 회차 추진", region: "와부읍", cat: "transport", department: "미래교통과" },
  { title: "월문천 일대 마을안길 우수관로 정비 추진", region: "와부읍", cat: "living", department: "상하수도관리센터" },
  { title: "지하철 6호선 연장 추진", region: "와부읍", cat: "transport", department: "미래교통과" },
  { title: "고려대 덕소농장 복원(시민 치유정원 조성)", region: "와부읍", cat: "environment", department: "공원조성과" },
  { title: "와부~화도2 구간 도로 선형개량 사업", region: "와부읍", cat: "transport", department: "도로건설과" },
  { title: "월문리IC 설치 및 마을회관 건립", region: "와부읍", cat: "transport", department: "도로건설과" },

  { title: "진건초교~사능역 보행로 개선 추진", region: "진건읍", cat: "transport", department: "도로건설과" },
  { title: "버스노선 정비 및 증차 운행 추진", region: "진건읍", cat: "transport", department: "대중교통과" },
  { title: "노후 공동주택 보수 지원 사업 확대 추진", region: "진건읍", cat: "living", department: "주택과" },
  { title: "송능리 건폐장 이전", region: "진건읍", cat: "environment", department: "자원순환과" },

  { title: "진건푸른물센터 조기 이전 추진", region: "다산1동", cat: "living", department: "하수처리과" },
  { title: "6호선 다산-왕숙2-양정-와부 연장 및 추가역사 신설 추진", region: "다산1동", cat: "transport", department: "미래교통과" },
  { title: "진건신규택지 추가 역사 신설", region: "다산1동", cat: "transport", department: "미래교통과" },
  { title: "다산복합커뮤니티센터 조기 착공 추진", region: "다산1동", cat: "culture", department: "공공건축과" },
  { title: "임시차고지 이전 후 주민편의시설 조성 추진", region: "다산1동", cat: "living", department: "도시정책과" },
  { title: "경의중앙선 상부 공원화 사업 적기 추진", region: "다산1동", cat: "environment", department: "공원조성과" },
  { title: "다산 ~ 왕숙2 4차로 연계도로 조기 착공", region: "다산1동", cat: "transport", department: "도로건설과" },
  { title: "인공암벽장 및 배트민턴(10면규모) 조기 착공 추진", region: "다산1동", cat: "culture", department: "체육지원과" },
  { title: "지방도 383호선 확장 적기 추진(왕숙 ~ 다산)", region: "다산1동", cat: "transport", department: "도로건설과" },
  { title: "경찰지구대 신설 추진", region: "다산1동", cat: "admin", department: "시민안전과" },
  { title: "공공도서관 신설", region: "다산1동", cat: "culture", department: "도서관정책과" },
  { title: "갈매IC 신설 추진", region: "다산1동", cat: "transport", department: "도로건설과" },
  { title: "북부간선도로 (일부구간) 6차선 확장 추진", region: "다산1동", cat: "transport", department: "도로건설과" },
  { title: "수도권 제1순환 지하고속도로 조기 착공 추진", region: "다산1동", cat: "transport", department: "도로건설과" },

  { title: "노후 공동주택 보수 지원 사업 확대 추진", region: "퇴계원읍", cat: "living", department: "주택과" },
  { title: "퇴계원~별내~다산역 교통 체계 정비 추진", region: "퇴계원읍", cat: "transport", department: "대중교통과" },
  { title: "퇴계원 산대놀이 관광 상품화 추진", region: "퇴계원읍", cat: "culture", department: "문화관광과" },

  { title: "도시재생사업 지원 확대 추진", region: "금곡동", cat: "living", department: "도시재생과" },
  { title: "노후주택 시설 보강 및 거주 안전 강화", region: "금곡동", cat: "living", department: "주택과" },
  { title: "시도 20호선(금곡사거리~시청앞) 확장 추진", region: "금곡동", cat: "transport", department: "도로건설과" },
  { title: "경춘로(진안사거리~금곡사거리) 확장 추진", region: "금곡동", cat: "transport", department: "도로건설과" },

  { title: "상수원 규제 합리화 추진", region: "조안면", cat: "environment", department: "환경정책과" },
  { title: "고령층을 위한 공공시설 순환 버스 추진", region: "조안면", cat: "transport", department: "대중교통과" },
  { title: "물의 도서관(가칭) 조기 착공 추진", region: "조안면", cat: "culture", department: "도서관정책과" },

  { title: "73사단 군부대 이전 추진", region: "양정동", cat: "living", department: "도시정책과" },
  { title: "삼패사거리 입체화 조기 착공 추진", region: "양정동", cat: "transport", department: "도로건설과" },
  { title: "왕숙2지구 연계 문화예술 복합단지 추진", region: "양정동", cat: "culture", department: "문화예술과" },
  { title: "9호선 왕숙2신설 역사 환승센터 건립", region: "양정동", cat: "transport", department: "미래교통과" },
  { title: "구 46번국도 (진안사거리~금곡) 6차로 확장 및 지하화", region: "양정동", cat: "transport", department: "도로건설과" },
  { title: "왕숙2~양정역세권 연결로 신설", region: "양정동", cat: "transport", department: "도로건설과" },
  { title: "국호6호선 확장(왕숙2~덕소삼패IC)", region: "양정동", cat: "transport", department: "도로건설과" },
  { title: "양정역 환승주차장 신설 추진(약223면 규모)", region: "양정동", cat: "transport", department: "주차관리과" },
  { title: "수석~호평간 고속화도로 연결로 추진(서울방향 IC)", region: "양정동", cat: "transport", department: "도로건설과" },
  { title: "양정동 복합청사 건립 추진", region: "양정동", cat: "admin", department: "청사건립추진단" },

  { title: "신청사 건립 추진", region: "다산2동", cat: "admin", department: "청사건립추진단" },
  { title: "9호선 조기 착공 및 적기 개통", region: "다산2동", cat: "transport", department: "미래교통과" },
  { title: "9호선 945역사 출입구 추가 증설 추진", region: "다산2동", cat: "transport", department: "미래교통과" },
  { title: "강변북로 지하 확장 추진(지상 6차로 + 지하4차로)", region: "다산2동", cat: "transport", department: "도로건설과" },
  { title: "가운복합커뮤니티센터 건립 추진", region: "다산2동", cat: "culture", department: "공공건축과" },
  { title: "수석대교 6차선 직결 추진", region: "다산2동", cat: "transport", department: "도로건설과" },
  { title: "황금산 근린공원 공공형 휴양시설 조성 추진", region: "다산2동", cat: "environment", department: "공원관리과" },
  { title: "남양주시체육문화센터 리뉴얼", region: "다산2동", cat: "culture", department: "체육지원과" },
  { title: "경기신용보증재단 조기이전 추진", region: "다산2동", cat: "economy", department: "기업지원과" },
  { title: "남양주-구리 행정구역 개편 후 수변문화공원 조성 추진", region: "다산2동", cat: "environment", department: "공원조성과" },
  { title: "주민상생형 우리은행 연수원 건립 지원", region: "다산2동", cat: "culture", department: "주민복지과" },
  { title: "공공도서관 건립 추진", region: "다산2동", cat: "culture", department: "도서관정책과" },
  { title: "다신지금로 보행특화거리조성", region: "다산2동", cat: "environment", department: "도로건설과" },

  { title: "폐열기반 스마트팜 클러스터 구축", region: "병구공통", cat: "environment", department: "환경정책과" },
  { title: "공항버스(4800번) 증차 및 김포공항 경유 노선 확보", region: "병구공통", cat: "transport", department: "대중교통과" },
  { title: "경유차 버스 친환경버스로 교체", region: "병구공통", cat: "environment", department: "대중교통과" },
  { title: "북한강/조안면 K-치유 생태 벨트 및 슬로우라이프 거점", region: "병구공통", cat: "environment", department: "환경정책과" }
]

const ALL_PLEDGES = [
  ...REAL_PLEDGES.map(p => ({ ...p, categoryId: p.cat, pledgeType: "regional" })),
  ...CATEGORY_PLEDGES.map(p => ({ ...p, department: "담당부서 지정 예정", region: "남양주 전역", pledgeType: "category" }))
]

export const MOCK_PLEDGES = ALL_PLEDGES.map((p, i) => ({
  id: `p-${i}`,
  title: p.title,
  schedule: "2024.01 ~ " + (2025 + (i % 3)) + ".12",
  department: p.department || "담당부서 지정 예정",
  budget: "해당사항 없음/추후 확정 반영(기금 등 활용)",
  status: POLICY_STATUSES[i % 3].id,
  categoryId: p.categoryId,
  region: p.region || "남양주 전역",
  pledgeType: p.pledgeType,
  targetAge: ["전체", "청년", "어르신", "아동", "청소년"][i % 5],
  matchRate: Math.floor(Math.random() * 20) + 80
}))
