export const CATEGORY_PLEDGES = [
  { title: "01. 남양주형 개발이익 환수 및 공공재투자 추진", categoryId: "future" },
  { title: "02. 남양주도시공사 참여지분 확대 및 공동시행권 확보", categoryId: "future" },
  { title: "03. 환수된 개발이익 GTX 및 생활SOC 재투자", categoryId: "future" },
  { title: "04. 왕숙 첨단 클러스터 조성", categoryId: "future" },
  { title: "05. 데이터 기반 첨단 제조·AI·바이오·에너지 융합 산업 유치", categoryId: "future" },
  { title: "06. 일터와 삶터가 가까운 직주근접 자족도시 완성", categoryId: "future" },
  { title: "07. 경기 경제자유구역 지정 및 추진단 설치", categoryId: "future" },
  { title: "08. 파격적 조세감면 및 규제특례 패키지 추진", categoryId: "future" },
  { title: "09. 금곡동 시청사 이전부지 창업허브 조성", categoryId: "future" },
  { title: "10. 데이터센터 국가산단급 첨단산업 거점 육성", categoryId: "future" },
  { title: "11. 왕숙-금곡-화도를 연결하는 미래산업벨트 구축", categoryId: "future" },
  { title: "12. 디지털 기술 및 친환경 에너지 절감형 첨단 복합산업단지 구축", categoryId: "future" },
  { title: "13. 시민 데이터 기반 '데이터연금' 체계 구축", categoryId: "future" },
  { title: "14. 드론 기술 검증 및 미래 모빌리티 산업 육성", categoryId: "future" },
  { title: "15. 청년 창업과 연계한 레저·스포츠·교육 거점도시 조성", categoryId: "future" },
  { title: "16. K-콘텐츠밸리 및 창작 메이커시티 조성", categoryId: "future" },
  { title: "17. 창작·디자인·공예 산업 집중 육성", categoryId: "future" },
  { title: "18. 청년 창작 인큐베이팅 및 메이커 스페이스 확대", categoryId: "future" },
  { title: "19. 창작과 산업이 연결되는 미래형 문화산업 기반 구축", categoryId: "future" },
  { title: "20. 남양주 컨벤션센터 추진으로 경제허브 확장(BY그룹 유휴시설 활용)", categoryId: "future" },
  { title: "01. 남양주 시민은행 설립 추진", categoryId: "economy" },
  { title: "02. 저신용자·소상공인·금융취약계층 대상 초저금리 소액대출 지원", categoryId: "economy" },
  { title: "03. 스타트업 투자 및 사회적 금융복지 확대", categoryId: "economy" },
  { title: "04. 지역화폐 인센티브 10% + 소비 캐시백 5% 확대", categoryId: "economy" },
  { title: "05. 소상공인 카드수수료 지원", categoryId: "economy" },
  { title: "06. 세입 소상공인 상가임차 면적 사용 권리 보장(임대차계약서와 실제 사용 면적 상이)", categoryId: "economy" },
  { title: "07. 전통시장 현대화 및 골목상권 활성화", categoryId: "economy" },
  { title: "08. 골목형 상점가 지정 확대 및 온누리상품권 사용처 확대", categoryId: "economy" },
  { title: "09. 상권활성화센터 정상 운영", categoryId: "economy" },
  { title: "10. 상인회 조직 활성화 지원", categoryId: "economy" },
  { title: "11. 건강진단결과서 발급 비용 전액 지원", categoryId: "economy" },
  { title: "12. 주차단속 유예 확대 추진", categoryId: "economy" },
  { title: "13. 시청 구내식당 휴무일 확대(월1회 -> 주1회)", categoryId: "economy" },
  { title: "14. 시청 구내식당 일반인 판매금지", categoryId: "economy" },
  { title: "15. 제2청사 저녁 외부 손님 받는 문제", categoryId: "economy" },
  { title: "16. 기업하기 좋은 환경 조성 및 스마트공장 구축 지원", categoryId: "economy" },
  { title: "17. 글로벌 시장 개척 및 마케팅 지원 확대", categoryId: "economy" },
  { title: "18. 남양주시 뿌리산업 경쟁력 강화", categoryId: "economy" },
  { title: "19. 가구·기계·가공산업 맞춤형 미니 산업단지 조성", categoryId: "economy" },
  { title: "20. 6차 가공산업 및 수출기지 육성", categoryId: "economy" },
  { title: "21. 고부가가치 산업 전환 및 R&D 인력 지원", categoryId: "economy" },
  { title: "22. 스마트팜 클러스터 및 치유농업 활성화", categoryId: "economy" },
  { title: "23. 데이터센터·소각장 폐열 활용 스마트팜 구축", categoryId: "economy" },
  { title: "24. 청년 스마트농업 스타트업 육성", categoryId: "economy" },
  { title: "25. 도시농업 및 치유농업 확대", categoryId: "economy" },
  { title: "26. 친환경 먹거리 자립체계 강화", categoryId: "economy" },
  { title: "27. 청년 경제독립사관학교 운영", categoryId: "economy" },
  { title: "28. 청년창업기업 도약 오디션 및 중견기업 육성 프로젝트", categoryId: "economy" },
  { title: "29. 실전 재테크·신용관리·전세사기 예방 교육 지원", categoryId: "economy" },
  { title: "30. 청년 경제 아카데미 운영", categoryId: "economy" },
  { title: "31. 정장 대여소 신설 및 청년기업 우대", categoryId: "economy" },
  { title: "32. 노동존중 행정 및 생활임금 확대", categoryId: "economy" },
  { title: "33. 플랫폼·이동노동자 쉼터 및 권익지원센터 설치", categoryId: "economy" },
  { title: "34. 감정노동자 보호 및 노동인권 지원체계 구축", categoryId: "economy" },
  { title: "35. 산업단지·물류센터 노동환경 개선", categoryId: "economy" },
  { title: "36. 필수노동자 지원 및 산업안전 강화", categoryId: "economy" },
  { title: "37. 단시간 일자리 최소생활노동시간 보장제", categoryId: "economy" },
  { title: "38. 건설 현장 '지역민 우선 고용, 지역장비 우선 참여' 활성화", categoryId: "economy" },
  { title: "39. 건설현장 불법고용, 불법하도급에 대해 관리감독 및 행정조치 강화", categoryId: "economy" },
  { title: "40. 공공발주현장의 표준근로계약서 작성 및 적정임금제 실태파악 및 개선", categoryId: "economy" },
  { title: "41. 건설산업 활성화를 위한 위원회 구성 및 노정협의 정례화", categoryId: "economy" },
  { title: "42. 노사민정 거버넌스 구축", categoryId: "economy" },
  { title: "43. 남양주시-(산하기관) 노동조합 교섭구조 마련", categoryId: "economy" },
  { title: "44. 남양주시노동권익센터 설립", categoryId: "economy" },
  { title: "45. 어르신 사회서비스형 일자리 확대", categoryId: "economy" },
  { title: "46. 어르신 지혜은행 설립 및 시니어 일자리 확대", categoryId: "economy" },
  { title: "47. 그냥드림 사업 추진(위기가구 먹거리·생필품 즉시 지원)", categoryId: "economy" },
  { title: "01. GTX-B/D/E/F 조기 추진 및 광역철도망 연계", categoryId: "transport" },
  { title: "02. 9호선·8호선·6호선 연장 및 3호선 덕소 연결 추진", categoryId: "transport" },
  { title: "03. 경춘선·수인분당선 직결 추진", categoryId: "transport" },
  { title: "04. 수석대교 6차선 직결 추진", categoryId: "transport" },
  { title: "05. 4호선 증차 추진", categoryId: "transport" },
  { title: "06. 수석호평 고속도로 출퇴근시간 요금 할인 추진", categoryId: "transport" },
  { title: "07. 상습정체구간 도로 확장 및 연계도로 신설", categoryId: "transport" },
  { title: "08. 권역별 무료 순환 셔틀버스 확대", categoryId: "transport" },
  { title: "09. 남양주형 똑버스(DRT) 전 권역 확대", categoryId: "transport" },
  { title: "10. 광역버스 집중 배차 및 버스노선 전면 개편", categoryId: "transport" },
  { title: "11. 주요 거점 및 전철역 연결 순환버스 통합 운영", categoryId: "transport" },
  { title: "12. 어르신·아동·청소년 무상 대중교통 지원", categoryId: "transport" },
  { title: "13. 광역버스 반값 정기권 도입", categoryId: "transport" },
  { title: "14. 남양주 G-Pass 도입", categoryId: "transport" },
  { title: "15. AI 기반 스마트 교통체계 구축", categoryId: "transport" },
  { title: "16. AI 신호제어 시스템 및 교차로 지체 최소화", categoryId: "transport" },
  { title: "17. 출퇴근 안심 시스템 구축", categoryId: "transport" },
  { title: "18. 폭설·폭우 대응 스마트 교통관리 강화", categoryId: "transport" },
  { title: "19. 보행자 중심 교통안전 강화", categoryId: "transport" },
  { title: "20. 어린이보호구역 개선 및 CCTV 확대", categoryId: "transport" },
  { title: "21. 스마트 안전 스쿨존 확대", categoryId: "transport" },
  { title: "22. 도심 밀집지역 공공주차장 확대", categoryId: "transport" },
  { title: "01. 시립 공동주택 관리공단 설립 추진", categoryId: "living" },
  { title: "02. 통합관리시스템 구축을 통한 반값 관리비 실현", categoryId: "living" },
  { title: "03. 공동주택 회계 투명성 강화 및 부패방지 추진", categoryId: "living" },
  { title: "04. 경비원·미화원 고용안정 확대", categoryId: "living" },
  { title: "05. 공동주택관리지원센터 설치 및 전문 컨설팅 지원", categoryId: "living" },
  { title: "06. 소규모 공동주택 관리 사각지대 해소", categoryId: "living" },
  { title: "07. 공동주택 우수관리단지 인센티브 확대", categoryId: "living" },
  { title: "08. 노후 공동주택 에너지 효율화 사업 지원", categoryId: "living" },
  { title: "09. 엘리베이터·외벽·주차환경 등 대규모 수선비 지원 확대", categoryId: "living" },
  { title: "10. 청년·신혼부부 이사비 지원", categoryId: "living" },
  { title: "11. 청년 임차보증금 이자 지원", categoryId: "living" },
  { title: "12. 구도심 재생 및 생활SOC 확충", categoryId: "living" },
  { title: "13. '내 집 앞 10분 생활권' 조성", categoryId: "living" },
  { title: "14. 어르신 중심 15분 생활권 구축", categoryId: "living" },
  { title: "15. 무장애 보행환경 및 생활환경 개선 확대", categoryId: "living" },
  { title: "16. 남양주형 '그냥 해드림센터' 운영", categoryId: "living" },
  { title: "17. 행정복지센터 생활수리 기동반 운영", categoryId: "living" },
  { title: "18. 농촌외곽지역 이동형 생활수리 서비스 운영", categoryId: "living" },
  { title: "19. 생활돌봄과 주거안전 결합형 주민체감 행정 구축", categoryId: "living" },
  { title: "20. 유니버셜디자인 도시 구축", categoryId: "living" },
  { title: "21. 월문리, 녹촌리 지형특화 힐링 주거단지 조성", categoryId: "living" },
  { title: "01. 전시민투표제 기반 '남양주 쓸모앱' 도입", categoryId: "admin" },
  { title: "02. 권역별·현안별 타운홀미팅, 시민해커톤 운영 등 숙의민주주의 확대", categoryId: "admin" },
  { title: "03. 시민청원 및 전자민주주의 활성화", categoryId: "admin" },
  { title: "04. 주민자치·마을공동체·공익활동 지원체계 구축", categoryId: "admin" },
  { title: "05. 주민참여예산 대폭 확대", categoryId: "admin" },
  { title: "06. 보여주기식·선심성 예산 정비 및 민생예산 전환", categoryId: "admin" },
  { title: "07. 읍면동장 주민추천제 도입 등 풀뿌리 자치 기반 강화", categoryId: "admin" },
  { title: "08. 생활예산 결정권 및 지역 자치권 강화", categoryId: "admin" },
  { title: "09. 시민 공무원 평가제 도입", categoryId: "admin" },
  { title: "10. 생활불편·안전 민원 선제 대응 강화", categoryId: "admin" },
  { title: "11. AI 기반 맞춤형 정책·지원사업 안내 시스템 구축", categoryId: "admin" },
  { title: "12. AI 기반 원스톱 민원행정 구현", categoryId: "admin" },
  { title: "13. '답답함 ZERO' 즉시 해결 행정 추진", categoryId: "admin" },
  { title: "14. 민원 즉시처리 및 결과 실시간 공개", categoryId: "admin" },
  { title: "15. 불법 현수막 즉각 정비 및 도시미관 개선", categoryId: "admin" },
  { title: "16. 스마트 현장기동대 운영", categoryId: "admin" },
  { title: "17. 도로·시설물·도시청결 스마트 관리체계 구축", categoryId: "admin" },
  { title: "18. 개방화장실 지정 및 유지 확대", categoryId: "admin" },
  { title: "19. 시청 별관 주차장 '민원인' 전용 지정", categoryId: "admin" },
  { title: "20. 헌법교육 조례 제정 등 '헌법친화도시' 조성", categoryId: "admin" },
  { title: "21. 헌법정신과 직접민주주의 강화를 위한 '주민주권센터' 설립", categoryId: "admin" },
  { title: "22. 시청 공무원 비위(?) 징계(주영상, 기후남, 이양희)", categoryId: "admin" },
  { title: "23. 개방화장실 확대 및 지원", categoryId: "admin" },
  { title: "24. 시청 별관 주차장 민원인 주차장 확대(현재 공무원 전용 주차장 사용)", categoryId: "admin" },
  { title: "25. 지방자치법 개정에 따른 조례 개정", categoryId: "admin" },
  { title: "26. 자민자치지원센터 및 자치지원관제 등 전담지원조직 구축", categoryId: "admin" },
  { title: "27. 주민자치 사업비 인상", categoryId: "admin" },
  { title: "28. 주민자치사업과 주민참여예산 연계 및 마을의제 실행체계 구축", categoryId: "admin" },
  { title: "01. 경기도립의료원 남양주병원 조기 착공 및 완공 추진", categoryId: "welfare" },
  { title: "02. 상급종합병원급 협력체계 구축 및 대학병원 유치 추진", categoryId: "welfare" },
  { title: "03. 어린이·여성 특화 공공의료체계 구축", categoryId: "welfare" },
  { title: "04. 공공의료 복합의료타운 조성", categoryId: "welfare" },
  { title: "05. '남양주 SOS 돌봄119' 운영", categoryId: "welfare" },
  { title: "06. 아픈아이 병원동행 및 안심돌봄 서비스 도입", categoryId: "welfare" },
  { title: "07. 방문주치의 및 밀착 간호 돌봄 확대", categoryId: "welfare" },
  { title: "08. 권역별 24시 달빛어린이병원 확대", categoryId: "welfare" },
  { title: "09. 희망콜·바우처택시 소아·응급환자 이동지원 확대", categoryId: "welfare" },
  { title: "10. 의료안심주택 및 스마트 헬스케어 구축", categoryId: "welfare" },
  { title: "11. 주거지원(장애인주택ㆍ주거생활서비스) 확대", categoryId: "welfare" },
  { title: "12. 민간 전문의 방문진료 참여 확대", categoryId: "welfare" },
  { title: "13. 원진녹색병원 남양주 유치 추진", categoryId: "welfare" },
  { title: "14. 24시간 긴급돌봄체계 구축", categoryId: "welfare" },
  { title: "15. 남양주형 돌봄센터 확대", categoryId: "welfare" },
  { title: "16. 아동 심리치유 '마음튼튼 세이브존' 운영", categoryId: "welfare" },
  { title: "17. 어린이 정신건강 지원사업 확대", categoryId: "welfare" },
  { title: "18. 어린이 예술 테마 놀이터 조성", categoryId: "welfare" },
  { title: "19. 어린이 안심보행구간 및 금연안심거리 조성", categoryId: "welfare" },
  { title: "20. 지역아동센터 생활복지사 연령 확대(60세 -> 70세)", categoryId: "welfare" },
  { title: "21. 지역아동센터 시설장 연령 확대(65세->70세)", categoryId: "welfare" },
  { title: "22. 지역아동센터 추가운영비 내 일부 임대료 사용 허용", categoryId: "welfare" },
  { title: "23. 지역아동센터 추가운영비 인상 필요", categoryId: "welfare" },
  { title: "24. 남양주형 지역아동센터 관련 조례 개정으로 안정적 운영 기반 마련", categoryId: "welfare" },
  { title: "25. 남양주돌봄연합회(지역아동센터연합) 공간 지원", categoryId: "welfare" },
  { title: "26. 폐쇄형 흡연부스 설치 확대", categoryId: "welfare" },
  { title: "27. 임산부 가사돌봄 및 난임지원 확대", categoryId: "welfare" },
  { title: "28. 출산축하금 인상 추진", categoryId: "welfare" },
  { title: "29. 독거어르신 AI 돌봄서비스 확대", categoryId: "welfare" },
  { title: "30. AI 돌봄로봇 및 위험감지 센서 보급", categoryId: "welfare" },
  { title: "31. 비대면 스마트 헬스케어 플랫폼 구축", categoryId: "welfare" },
  { title: "32. 어르신 통합돌봄 및 보행 15분 생활권 구축", categoryId: "welfare" },
  { title: "33. 어르신 주거환경 개선 및 안전바 설치", categoryId: "welfare" },
  { title: "34. 경로당·마을회관 환경정비 및 방역 강화", categoryId: "welfare" },
  { title: "35. 노인정 식사 양질의 반찬 제공", categoryId: "welfare" },
  { title: "36. 어르신 건강점검 시스템 구축", categoryId: "welfare" },
  { title: "37. 키오스크 등 고령자 디지털 교육 확대", categoryId: "welfare" },
  { title: "38. 어르신 지혜은행 설립 및 노인일자리 확대", categoryId: "welfare" },
  { title: "39. 장애인 이동권 확대 및 특별교통수단 확충", categoryId: "welfare" },
  { title: "40. 저상버스 확대 및 교통약자 이동지원 강화", categoryId: "welfare" },
  { title: "41. 장애인 건강주치의 및 공공재활서비스 확대", categoryId: "welfare" },
  { title: "42. 장애인 평생교육 및 직업훈련 강화", categoryId: "welfare" },
  { title: "43. 장애인 시민참여위원회 및 정책협의체 운영", categoryId: "welfare" },
  { title: "44. 발달장애인 가족휴식·긴급돌봄·자립지원 확대", categoryId: "welfare" },
  { title: "45. 독립 발달장애인 활동지원 월200시간 추가 지원", categoryId: "welfare" },
  { title: "46. 발달장애인 일상생활배상책임보험 조례 제정 및 지원", categoryId: "welfare" },
  { title: "47. 장애인 보호작업장 확충 및 일자리 확대", categoryId: "welfare" },
  { title: "48. 장애인 어린이집 편중 입지(화도지역만 세 곳 입지), 동부장애인복지센터 입지 예정", categoryId: "welfare" },
  { title: "49. 장애린 어린이집 보조교사 지원 기준 및 근거 투명성 제고 필요", categoryId: "welfare" },
  { title: "50. 장애인 어린이집 연장반 운영 지원 기준 및 근거 투명성 제고 필요", categoryId: "welfare" },
  { title: "51. 장기 요양 기관 운영지원센터 설치", categoryId: "welfare" },
  { title: "52. 장기 요양 종사자 처우개선 지원사업 확대", categoryId: "welfare" },
  { title: "53. 재가 및 주야간보호센터 운행 차량 서비스 지원 확대", categoryId: "welfare" },
  { title: "54. 치매ㆍ중증 어르신 전문 돌봄 지원체계 구축", categoryId: "welfare" },
  { title: "55. 장기 요양 기관 시설환경 지원사업", categoryId: "welfare" },
  { title: "56. 지역 통합돌봄(커뮤니티케어) 강화", categoryId: "welfare" },
  { title: "57. 장기 요양 기관 공공성 강화 및 정책협의회 구성", categoryId: "welfare" },
  { title: "58. 장기 요양 기관 복지정책관 임명", categoryId: "welfare" },
  { title: "59. 비휠체어 교통약자 바우처택시 확대", categoryId: "welfare" },
  { title: "60. 보훈 메모리얼파크 조성 및 보훈수당 개편", categoryId: "welfare" },
  { title: "61. 현충탑 접근성 개선", categoryId: "welfare" },
  { title: "62. 남양주 어린이비전센터 현대화 및 프로그램 확대", categoryId: "welfare" },
  { title: "63. 남양주 체력인증센터 88365 운영", categoryId: "welfare" },
  { title: "64. 재난 발생 즉기 긴급돌봄 가동 체계 구축", categoryId: "welfare" },
  { title: "65. 남양주사회복지협의회 운영 지원(인건비, 운영비)", categoryId: "welfare" },
  { title: "66. 남양주시사회복지협의회 운영 지원(사무공간, 제도적 기반 등)", categoryId: "welfare" },
  { title: "67. 사회복지종사자 처우개선", categoryId: "welfare" },
  { title: "68. 남양주시사회복지관 동부희망케어센터 공간 지원", categoryId: "welfare" },
  { title: "69. 남양주시장애인복지관 인력지원", categoryId: "welfare" },
  { title: "70. 남양주시장애인가족지원센터 운영 인력 증원", categoryId: "welfare" },
  { title: "71. 초고령사회 대응을 위한 노인복지관 가능 및 지원체계 강화", categoryId: "welfare" },
  { title: "72. 노인보호전문기관 조사 과정의 공정성 확보", categoryId: "welfare" },
  { title: "73. 남양주시가족센터 공간 지원", categoryId: "welfare" },
  { title: "74. 약사, 한약사 업무범위 명확화", categoryId: "welfare" },
  { title: "75. 불법, 편법적 창고형 약국 확산 방지", categoryId: "welfare" },
  { title: "76. 공공심야약구 운영 및 지원 확대", categoryId: "welfare" },
  { title: "77. 통합돌봄 내 약사 참여 의무화", categoryId: "welfare" },
  { title: "78. 보건의료 취약지역 방문약사 및 약료서비스 확대", categoryId: "welfare" },
  { title: "79. 지역 공공의료기관 성분명처방 실시", categoryId: "welfare" },
  { title: "80. 명절연휴 운영약국 지원", categoryId: "welfare" },
  { title: "81. 지역 공공병원 약사 인력 확충", categoryId: "welfare" },
  { title: "82. 16개 읍면동 근골격 건강진단센터 설립", categoryId: "welfare" },
  { title: "83. 지역사회보장협의체 중심의 촘촘한 복지네트워크 강화", categoryId: "welfare" },
  { title: "01. 여성센터 건립 추진", categoryId: "youth" },
  { title: "02. 여선단체지원", categoryId: "youth" },
  { title: "03. 여성안심 귀갓길 및 안심조명 확대", categoryId: "youth" },
  { title: "04. 디지털 성범죄·스토킹 통합대응체계 구축 및 강화", categoryId: "youth" },
  { title: "05. 스토킹 범죄 예방을 위한 '사전예약제' 실시", categoryId: "youth" },
  { title: "06. 경력단절 여성 재취업·창업 지원 확대", categoryId: "youth" },
  { title: "07. 여성 1인가구 안전지원 강화", categoryId: "youth" },
  { title: "08. 공공·생활 인프라 성인지 관점 확대", categoryId: "youth" },
  { title: "09. 돌봄과 안전이 연결되는 여성친화도시 조성", categoryId: "youth" },
  { title: "10. 여성 권익증진 및 역량강화를 위한 여성센터 추진", categoryId: "youth" },
  { title: "11. 여성 생애주기별 맞춤형 건강지원'여성건강지원'", categoryId: "youth" },
  { title: "12. 여성청소년 생리대 보편지원 추진", categoryId: "youth" },
  { title: "13. 여성친화형 대피소 설계 기준 제도화", categoryId: "youth" },
  { title: "14. 성평등고용공시제 추진", categoryId: "youth" },
  { title: "15. 직장 내 성희롱 괴롭힘 보호", categoryId: "youth" },
  { title: "16. 양질의 여성일자리 창출", categoryId: "youth" },
  { title: "17. 단시간 일자리 최소생활노동시간 보장제", categoryId: "youth" },
  { title: "18. 탄소중립ㆍ기후위기 대응 조례에 성별영향평가 의무화", categoryId: "youth" },
  { title: "19. 청년 문화패스 및 생활문화 지원", categoryId: "youth" },
  { title: "20. 청년 정책참여 플랫폼 운영", categoryId: "youth" },
  { title: "21. 역세권 청년주거 공급 확대", categoryId: "youth" },
  { title: "22. 청년 창업 지원 확대 및 청년기업 우대", categoryId: "youth" },
  { title: "23. 청년 공유오피스 및 창작공간 확대", categoryId: "youth" },
  { title: "24. 청년 지역정착 인센티브 지원", categoryId: "youth" },
  { title: "25. 창업·주거·문화가 연결되는 청년 정착 생태계 구축", categoryId: "youth" },
  { title: "01. 1,000석 이상 대형 문화예술회관(아트센터) 조성", categoryId: "culture" },
  { title: "02. 오페라·뮤지컬·K-POP 등 시민 문화향유 확대", categoryId: "culture" },
  { title: "03. '조선로열 이음(IEUM)' 역사문화벨트 조성", categoryId: "culture" },
  { title: "04. 광릉·사릉·홍유릉 역사탐방 루트 구축", categoryId: "culture" },
  { title: "05. 황실문화센터 건립 추진", categoryId: "culture" },
  { title: "06. 정약용유적지~실학박물관~다산생태공원 역사문화테마지구 조성", categoryId: "culture" },
  { title: "07. 왕숙천·북한강 수변 복합문화공간 조성", categoryId: "culture" },
  { title: "08. 왕숙천·한강변 K-문화벨트 구축", categoryId: "culture" },
  { title: "09. 남양주형 공공 수변테라스 조성", categoryId: "culture" },
  { title: "10. 모란공원 민주열사 묘역 성지화 추진", categoryId: "culture" },
  { title: "11. 민주주의 역사공원 및 민주시민교육 확대", categoryId: "culture" },
  { title: "12. 전국 민주주의 교육·추모 거점 육성", categoryId: "culture" },
  { title: "13. 공원·아파트·골목 찾아가는 문화공연 확대", categoryId: "culture" },
  { title: "14. 찾아가는 문화버스·순회공연 운영", categoryId: "culture" },
  { title: "15. 생활문화동아리 및 문화사랑방 확대", categoryId: "culture" },
  { title: "16. 생활문화센터 및 권역별 문화예술 특성화 추진", categoryId: "culture" },
  { title: "17. 독립서점·동네책방 문화생태계 복원", categoryId: "culture" },
  { title: "18. 독립서점 프로그램 확대 및 도서구입비 지원", categoryId: "culture" },
  { title: "19. 북페어 개최 및 전국독서대전 유치 추진", categoryId: "culture" },
  { title: "20. 책 읽는 시민, 인문도시 남양주 조성", categoryId: "culture" },
  { title: "21. 남양주 대표 영화제·예술제 개최", categoryId: "culture" },
  { title: "22. 문화ㆍ예술분야 예산 순차적 확대", categoryId: "culture" },
  { title: "23. 예술인 창작지원금 및 창작공간(레지던시) 확대", categoryId: "culture" },
  { title: "24. 지역 연계형 예술인 레지던시 운영", categoryId: "culture" },
  { title: "25. 예술단체 공간·재정 지원 확대", categoryId: "culture" },
  { title: "26. 문화예술위원회 구성 및 민관 협치체계 구축", categoryId: "culture" },
  { title: "27. 문화예술 활성화를 위한 제도 및 조례 개선 추진", categoryId: "culture" },
  { title: "28. 문화바우처 확대를 통한 문화기본권 보장", categoryId: "culture" },
  { title: "29. 공연·전시·서점·공방 등 생활문화 접근성 확대", categoryId: "culture" },
  { title: "30. 이주민·취약계층 문화예술 지원 강화", categoryId: "culture" },
  { title: "31. 시민 누구나 문화를 누리는 생활문화도시 조성", categoryId: "culture" },
  { title: "32. 지역대표 축제 및 문화관광 콘텐츠 육성", categoryId: "culture" },
  { title: "33. 커피축제 추진", categoryId: "culture" },
  { title: "34. 역사·문화·관광·상권이 연결되는 체류형 문화도시 조성", categoryId: "culture" },
  { title: "35. 왕숙천·북한강 수변 힐링 문화도시 조성", categoryId: "culture" },
  { title: "36. 권역별 파크골프장 확대 및 생활체육 활성화", categoryId: "culture" },
  { title: "37. 체육시설 공동 이용 확대 및 불법 상태 해소(체육문화센터 운영개편안 철회)", categoryId: "culture" },
  { title: "38. 러너스테이션 및 러닝·맨발걷기 코스 조성", categoryId: "culture" },
  { title: "39. 남양주 전역 걷기길·힐링 산책로 연결", categoryId: "culture" },
  { title: "40. 반려동물 복합테마파크 조성", categoryId: "culture" },
  { title: "41. 축령산 트레일러닝대회 개최", categoryId: "culture" },
  { title: "01. 권역별 시민캠퍼스 및 시민대학 운영", categoryId: "education" },
  { title: "02. 은퇴설계 및 재취업 지원 시민캠퍼스 운영", categoryId: "education" },
  { title: "03. 민주주의교육 및 민주시민교육 확대", categoryId: "education" },
  { title: "04. 주민자치·마을공동체·사회적경제 활동 지원", categoryId: "education" },
  { title: "05. 왕숙 첨단클러스터 연계 미래산업 교육 강화", categoryId: "education" },
  { title: "06. AI·바이오·미래차 산학협력 체계 구축", categoryId: "education" },
  { title: "07. AI·바이오 융복합 클러스터 연계 교육과정 신설", categoryId: "education" },
  { title: "08. 특성화고 및 미래산업 교육 확대", categoryId: "education" },
  { title: "09. 청소년 진로케어 플랫폼 및 미래직업 체험관 구축", categoryId: "education" },
  { title: "10. VR·AR 미래직업 체험관 구축", categoryId: "education" },
  { title: "11. 진학~취업 연계 교육플랫폼 구축", categoryId: "education" },
  { title: "12. 남양주형 돌봄센터 확대", categoryId: "education" },
  { title: "13. 안전한 등하굣길 조성", categoryId: "education" },
  { title: "14. 교육비 부담 완화 및 1인1스포츠·1인1악기 지원", categoryId: "education" },
  { title: "15. 학교시설 복합 문화공간 조성", categoryId: "education" },
  { title: "16. 공공 와이파이망 확대", categoryId: "education" },
  { title: "17. 디지털 학습기기 및 온라인강의 지원", categoryId: "education" },
  { title: "18. 에너지 데이터 리터러시 교육 도입", categoryId: "education" },
  { title: "19. 남양주 독립 교육지원청 추진", categoryId: "education" },
  { title: "20. 화도권 고등학교 신설 및 과밀학급 정상화", categoryId: "education" },
  { title: "21. 학교시설 복합화 및 시민 개방형 교육문화공간 확대", categoryId: "education" },
  { title: "22. 찾아가는 학부모 교육센터(지역별 소규모 설명회)", categoryId: "education" },
  { title: "23. 다문화ㆍ외국인가정 교육 연결 지원", categoryId: "education" },
  { title: "24. 학생 성장형 문화ㆍ진로 공간 확대", categoryId: "education" },
  { title: "25. 시니어 교육멘토단 운영", categoryId: "education" },
  { title: "01. 시민참여형 햇빛발전 및 햇빛연금 확대", categoryId: "environment" },
  { title: "02. 공공 RE100 기반 에너지 자립도시 추진", categoryId: "environment" },
  { title: "03. '남양주형 그린페이' 등 에너지 마일리지 도입", categoryId: "environment" },
  { title: "04. 공공청사·공공시설 태양광 확대", categoryId: "environment" },
  { title: "05. 에너지 자립마을 확대 지원", categoryId: "environment" },
  { title: "06. 수소도시 조성 추진", categoryId: "environment" },
  { title: "07. 폐기물 에너지화 기반 자원순환단지 조기 완공", categoryId: "environment" },
  { title: "08. 미세먼지 차단 도시숲 확대", categoryId: "environment" },
  { title: "09. 폭염 대응 그늘쉼터 및 쿨루프 확대", categoryId: "environment" },
  { title: "10. 생활악취·미세먼지 스마트 대응체계 구축", categoryId: "environment" },
  { title: "11. 하천·생활녹지 연결 녹색네트워크 확대", categoryId: "environment" },
  { title: "12. 걷고 쉬기 좋은 생활권 녹색도시 조성", categoryId: "environment" },
  { title: "13. 폭설·침수 등 기후재난 대응 스마트 시스템 구축", categoryId: "environment" },
  { title: "14. 소규모 산업단지 안전 인프라 구축 및 화재예방 시스템 강화", categoryId: "environment" },
  { title: "15. 기후먹거리 전환", categoryId: "environment" },
  { title: "16. 상수원보호구역 규제 합리화", categoryId: "environment" }
];
